### ISSUE TITLE
Register transport-level interceptors per-handler

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#156] opened 2016-05-27 23:17 UTC
It's possible that we'll need to be able to apply transport interceptors on a per-handler basis - for example, protecting a subset of handlers with a certain auth interceptor:

```
rpc.AddInterceptor([myService.ThisProcedure, myService.ThatProcedure], SuperStrongAuthInterceptor{})
```

Brought up by @shawnburke

@yarpc/golang thoughts? Is this the right path or is there a better way to think about this?

**Comment by kriskowal** [comment] 2016-05-27 23:27
Our experience with Node.js HTTP service libraries has been that every method should have its own middleware chain, configured by the application writer. It’s important to avoid answering the question, “How do the global middleware and the per-method middleware get interleaved”. No answer to that question is suitable for every application. That is a question that only the application writer can answer. Each application may have its own utilities for generating common middleware chains.

cc @Matt-Esch @Raynos

**Comment by kriskowal** [comment] 2016-05-27 23:36
@breerly brings up the point offline that we want to configure middleware like auth in one-line-init libraries and take that out of the hands of application writers.

To avoid the question of interleaving per-method and per-application middleware, we can also say "no per-method middleware". I expect that answer to be unsatisfying to application authors.

**Comment by breerly** [comment] 2016-05-27 23:46
I think in the case of authz middleware, you'll have something like this:

1. Someone authors permissions in some UI somewhere.
2. Those permissions end up in a service/data source somewhere.
3. An authz middleware is plugged in to one-line init that looks at the metadata of a request (service and procedure name) and raises a native-YARPC authz error that is understood on both sides of the wire.

For authn, I imagine you'd want that plugged in in one-line init as well.

Both of these should use *global* transport-level middleware, not per-handler.

**Comment by breerly** [comment] 2016-05-27 23:48
@kriskowal what type of reasons, outside of auth, did people have for per-handler middleware?

**Comment by abhinav** [comment] 2016-05-28 00:04
Per-handler middleware open up questions about interaction/ordering with global interceptors that we may not have good answers for right now, before having released v1. Besides that, it's easy to imagine people misusing per-handler middleware by implementing business logic inside it under the guise of avoiding duplication. This is something we should very explicitly discourage with both, documentation and API design. If middleware needs to be special cased for a specific set of handlers, maybe that logic should simply be part of those handlers. I'm happy to reconsider this position if we can find real examples of situations where we need per-handler middleware which can't be part of the handler itself.

For v1, I think we can get away with taking the opinionated stance of global interceptors only. Once we're convinced that we actually need per-handler middleware, and have found good answers to questions around their interaction with global middleware (and other semantics), we can implement and support it later with fairly low cost. On the other hand, starting with per-handler middleware right out the door is not something we can cheaply reconsider after release.

**Comment by Raynos** [comment] 2016-05-28 00:27
Middlewares are all about a framework exposing extension hooks. It makes sense to have some form of global extension hooks, in whatever form you think makes sense.

Most applications actually don't use per handler middlewares and the services that do have custom needs that are hard to satisfy in a general system like yarpc.

Generally "less is more", if there is no need to extend the framework on a per handler basis then I wouldn't implement it.

**Comment by shawnburke** [comment] 2016-05-28 18:01
@breerly  I think we're mixing a policy and a technology conversation.  In other words, there is a world where an organization might have a centralized AuthZ UX that allows configuring all of this stuff: that's policy because it's up to people not involved with this project to make that call.  FWIW, last I checked that is _not_ the current path for our system.  That might change, as is typical with policy.   The _technology_ conversation for this layer has to do what types of scenarios we want to enable.  It's a great place to be in if your technology is sufficiently flexible to enable whatever policy the business decides to apply.

So, in the near future we're likely to need per-endpoint middleware.

For other examples of what you might want to do here on a per-handler basis:

- Extended logging or logging to a special place for diagnostics
- Traffic shadowing or T
- Data transforms, encryption, compression, or filters
- Etc...

This is the kind of thing you sometimes don't completely understand your need for but then it becomes massively useful in esoteric scenarios.

**Comment by kriskowal** [comment] 2016-11-10 22:29
I have added this to the 1.0.0 milestone. We may elect to punt on it, but this is related to ongoing work for forwarding middleware, since one of the use-cases is handle-or-forward middleware that would be appropriate to apply per channel or per procedure.

**Comment by kriskowal** [comment] 2016-12-02 19:02
I’m moving this to post 1.0 triage. I don’t expect that we would need to make a breaking change to support this, but if we do, we have run out of time to land them in 1.0.

**Comment by kriskowal** [comment] 2017-04-11 22:18
2¢

* Per-procedure middleware can be faked today with global middleware that falls through early if the request doesn’t match the desired procedure. This avoids the issue of interleaving global and per-procedure middleware entirely.
* IDL generates registration code and middleware chains are created upon registration. If we had per-procedure middleware, it would likely have to be applied as options to the Register call. We should avoid unwinding or topo sorting middleware. I thought that was a good idea, but I’m now convinced that it’s surprising and not terribly useful in practice.

I don’t think this will be on our roadmap this year, so I’m going to close the issue for now, instead of letting it stagnate in the backlog. I believe we’re sympathetic to the cause when a concrete use-case comes up, so please re-open the conversation if you’ve got one.

**Closed by kriskowal** 2017-04-11 22:18 UTC
Labels: enhancement
