### ISSUE TITLE
Discuss removing req/res meta

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#617] opened 2016-12-17 02:12 UTC
What is the API that users expect? I'll bet it's something like this:

```go
resp, err := client.Call(ctx, req)
```

and for handlers:

```go
func (handler) Call(ctx context.Context, e *service.Request) (*service.Response, error) {
	return &service.Response{}, nil
}
```

But what about metadata?

### Outbound Metadata

For outbound metadata, like headers, I think that riding the context is a fine option:

```go
resp, err := client.Call(yarpc.WithHeaders(ctx, {"blah": "blah"}), req)

func (handler) Call(ctx context.Context, e *service.Request) (*service.Response, error) {
        headers := yarpc.GetHeaders(ctx)
	return &service.Response{}, nil
}
```

### Inbound Metadata

For inbound metadata, we likely need to return *something* from the handler:

```go
func (handler) Call(ctx context.Context, e *service.Request) (*service.Response, yarpc.ResMeta, error) {
	return &service.Response{}, nil, nil
}
```

And to receive inbound metadata at outbound callsites, we can use the options pattern:

```go
resMeta := make(yarpc.ResMeta)
resp, err := client.Call(ctx, req, yarpc.WithResMeta(resMeta))
```

Alot of this is pseudo-code, but I just wanted to get some ideas out there.

**Comment by kriskowal** [comment] 2016-12-19 19:17
Perhaps the smell with reqMeta and resMeta is the Meta. The metas *are* the request and response, sans body. So maybe this weird trick of naming helps.

* reqMeta, req -> req, arg
* resMeta, res -> res, ret

This and many other inevitable rehashings since the issue is open.

**Comment by breerly** [comment] 2016-12-19 23:51
Here's grpc-go's approach: https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md

**Comment by akshayjshah** [comment] 2016-12-20 18:21
My $0.02: I'd expect the context to encapsulate multi-hop information and deadlines, and I'd expect the request and response structs to include body and meta fields. This maps closely to the mental model I have for "standard" HTTP, and to me it's the least confusing.

The main downside I see is the increased amount of code gen - even if the meta/headers/whatever shape is common, we'll need to generate handler-specific request and response shapes in addition to the body shapes.

**Comment by prashantv** [comment] 2016-12-20 20:07
I'm for removing req meta/res meta, but we need to be very careful with how we add these fields to the context. The headers on `thrift.Context` in tchannel-go have caused a few pain points:
 - No separation between incoming headers and outgoing headers, so when you make an outbound call using the same context, it copies all headers (which is *not* what we normally want)
 - Avoid race conditions when the same context is used for further downstream calls in parallel

**Comment by kriskowal** [comment] 2016-12-20 21:35
Offline, @akshayjshah floats the idea (valued also at 2¢) that code for request and response types are generated per request, such that regardless of the procedure, they satisfy a request metadata interface that passes through middleware.

**Comment by peter-edge** [comment] 2016-12-21 08:26
I might be misunderstanding, but are you basically thinking (referencing the thrift keyvalue example service):

```go
type Interface interface {
  SetValue(ctx context.Context, request *SetValueRequest) (*SetValueResponse, error)
  ...
}

type SetValueRequest struct {
  Key *String
  Value *String
  Meta something.Meta
}

// desirable even if void? pros and cons
type SetValueResponse struct {
  Meta something.Meta
}
```

The big negative of this to me at least is that if the function signature changes, the generated code signature does not change, just the fields of the generated request/responses, and while if a parameter is removed, renamed, or changes types, dependent code will break, adding a parameter will not break any code, which could leave for unhandled parameters. The `SetValueResponse` case is especially bad for that, ie if a function went from returning `void` to returning some value that should be checked.

**Comment by blampe** [comment] 2016-12-21 20:09
@madhuravi gave us similar feedback about req/resmeta being confusing. We had a good discussion around alternatives that @abhinav will summarize.

**Comment by abhinav** [comment] 2016-12-21 21:36
From the new discussion, we seem to have agreement about the following:

-   We drop `ReqMeta`, `ResMeta`, `CallReqMeta`, and `CallResMeta` completely.
-   Client side:

    -   `context.Context` is used to pass in request headers.
    -   Clients accept `yarpc.ClientOption` varargs
    -   Response headers are made available through a `yarpc.ResponseHeaders`
        option

    So the client interface becomes,
    
    ```go
    type Interface struct {
        GetValue(context.Context, *GetValueRequest, ...yarpc.ClientOption) (*GetValueResponse, error)
        SetValue(context.Context, *SetValueRequest, ...yarpc.ClientOption) (*SetValueResponse, error)
    }
    ```
    
    We would provide a `yarpc.ResponseHeaders` option,
    
    ```go
    res, err := client.GetValue(ctx, req)   // no headers
    
    // with headers
    var responseHeaders yarpc.Headers
    res, err := client.GetValue(
        yarpc.WithHeaders(ctx, requestHeaders),
        req,
        yarpc.ResponseHeaders(responseHeaders),
    )
    ```

-   Server side:

    -   Request headers will be retrieved from the context.
    -   Response headers will be written to the context.
    -   Implementation detail: Incoming request headers and outgoing request
        headers will use different `context.Value` keys so that all incoming
        headers are not automatically sent as outgoing headers.

    ```go
    func (h *handler) GetValue(ctx context.Context, req *GetValueRequest) (*GetValueResponse, error) {
        requestHeaders := yarpc.GetHeaders(ctx)
        yarpc.SetResponseHeaders(ctx, responseHeaders)
        return res, err
    }
    ```

This simplifies the common use case significantly. The specifics of the APIs
are open to iteration but what do you guys think about this in general?

CC @yarpc/golang

**Comment by madhuravi** [comment] 2016-12-21 21:56
+1 Looks great. I am in favor of removing yarpc.Options also so client side would be -
```
type Interface struct {
    GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error)
    SetValue(context.Context, *SetValueRequest) (*SetValueResponse, error)
}
```
 but I remember @prashantv or @abhinav had a reason why we needed that. Can you call that out as well?

**Comment by kriskowal** [comment] 2016-12-21 22:08
I don’t like inflating the context for single hop metadata, and I think this panders to example cases instead of use cases, but, I believe we could live with this.

I advise being skeptical of things that look "simpler" because they are smaller, when they in fact combine separate things (the definition of "complicate").

@abhinav's proposal eliminates the ugliness of the meta builder pattern, but I think there are other cures for that problem.

```go
req := yarpc.NewRequest()
req.SetHeader(k1, v1)
req.SetHeader(k2, v2)
val, res, err := client.GetValue(ctx, req, arg)
v3 := res.Header(k3)
v4 := res.Header(k4)
```

```go
func (h *handler) GetValue(ctx context.Context, req yarpc.Request, arg GetValueArgument) GetValueResult, yarpc.Response, error {
    v1 := req.Header(k1)
    v2 := req.Header(k2)
    res := yarpc.NewResponse()
    res.SetHeader(k3, v3)
    res.SetHeader(k4, v4)
    return val, res, nil
}
```

To reiterate, I believe we can live with the proposal that "complicates" multi-hop and single-hop metadata on context.Context, and I reemphasize the counter-argument to ensure it gets due consideration.

In general, when zeroing in on a final design, the Go idiom is SetX/X, not SetX/GetX.

**Comment by abhinav** [comment] 2016-12-21 22:34
@madhuravi The vararg options exist so that we can provide
`yarpc.ResponseHeaders(..)` as an option. Otherwise, it would have to be on
the context somehow.

    var responseHeaders yarpc.Headers
    ctx = yarpc.WriteResponseHeaders(ctx, responseHeaders)
    res, err := client.GetValue(ctx, req)

---

@kriskowal Unfortunately there's no perfect solution for this. Ideally, we
wouldn't have to conflate these concerns but there has been consistent
negative feedback about this. Calling them `Request` and `Response` helps but
people still dislike the extra argument and return value which are meaningless
for the majority case.

RE: SetX/X: Sounds good.

**Comment by kriskowal** [comment] 2016-12-22 21:03
Assigned to @abhinav to carry fitting changes into 1.0.0.

**Comment by abhinav** [comment] 2016-12-23 01:36
Tracking the changes here:

- [x] Client-side APIs #648 
- [ ] Server-side APIs
- [x] Raw client #647
- [ ] Raw server
- [ ] JSON client
- [ ] JSON server
- [ ] Thrift client
- [ ] Thrift server

**Closed** 2016-12-27 19:35 UTC
